[prompt]
summary_all = "這是今日的 Hacker News 前十大新聞，以綜合分析的方式進行概括，並條列出各新聞的主要重點。同時，請將各項新聞中最重要的一項與其相關的關鍵字突顯出來。最後，請以適當的段落劃分，並以('\n\n')作為分段符號。always response in zh-tw: "
summary_single = "請用2-3句話簡潔摘要這則 Hacker News 新聞的重點。不要超過100字。always response in zh-tw: "
get_language_code = "identify the input is which language, and response it only to ISO 639-1 standard language codes and country code without any more explaination, if input is Chinese, always return zh-tw: "
translate = "translate to "
